User.create(username: "jon", password: "jon")
User.create(username: "adam", password: "adam")
User.create(username: "yaya", password: "yaya")


List.create(title: "Toru's todos")
List.create(title: "Your cat's day")
List.create(title: "totoro's todos")

Item.create(goal: "quit job", list_id: 1)
Item.create(goal: "Cook dinner for the wife", list_id: 1)
Item.create(goal: "Find cat", list_id: 1)
Item.create(goal: "find your wife", list_id: 1)
Item.create(goal: "sleep", list_id: 2)
Item.create(goal: "eat", list_id: 2)
Item.create(goal: "sleep some more", list_id: 2)
Item.create(goal: ":)", list_id: 3)
Item.create(goal: "umbrella", list_id: 3)
Item.create(goal: "furballs", list_id: 3)
Item.create(goal: "catbus", list_id: 3)
